# .github/workflows/flutter_firebase.yml
name: Build and Distribute Flutter App (Android)

on:
  push:
    branches:
      - main

jobs:
 distribute_to_firebase:
    name: Build and Distribute
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My repo Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
          working-directory: android

      - name: Install dependencies via Bundler
        run: bundle install
        working-directory: android

      - name: Distribute via Firebase
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android

